installing_message = "Reminder: Citra is an <b>experimental</b> emulator. Stuff may break!"
hide_advanced = true

[[packages]]
name = "Citra Nightly"
description = "The Nightly build of Citra contains features that have already been reviewed and tested."
    [packages.source]
    name = "github"
    match = "^citra-windows-mingw-[0-9]*-[0-9a-f]*.tar.gz$"
        [packages.source.config]
        repo = "citra-emu/citra-nightly"
    [[packages.shortcuts]]
    name = "Citra Nightly"
    relative_path = "nightly/citra-qt.exe"
    description = "Launch Citra (Nightly build)"

[[packages]]
name = "Citra Canary"
description = "The Canary build of Citra contains in-development features that are yet to be fully reviewed and tested."
default = true
    [packages.source]
    name = "github"
    match = "^citra-windows-mingw-[0-9]*-[0-9a-f]*.tar.gz$"
        [packages.source.config]
        repo = "citra-emu/citra-canary"
    [[packages.shortcuts]]
    name = "Citra Canary"
    relative_path = "canary/citra-qt.exe"
    description = "Launch Citra (Canary build)"
