installing_message = "Reminder: Citra is an <b>experimental</b> emulator. Stuff may break!"
hide_advanced = true

[[packages]]
name = "Citra Nightly"
description = "The Nightly build of Citra contains features that have already been reviewed and tested."
    [packages.source]
    name = "github"
    match = "^citra-linux-[0-9]*-[0-9a-f]*.tar.xz$"
        [packages.source.config]
        repo = "citra-emu/citra-nightly"

[[packages]]
name = "Citra Canary"
description = "The Canary build of Citra contains in-development features that are yet to be fully reviewed and tested."
default = true
    [packages.source]
    name = "github"
    match = "^citra-linux-[0-9]*-[0-9a-f]*.tar.xz$"
        [packages.source.config]
        repo = "citra-emu/citra-canary"

